In [ ]:
# Question:1

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Sample scalar and array inputs
scalar = 3.7
arr = np.array([1.2, 2.3, -3.4, 4.5, 5.7,-6.8])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)

sin: [ 0.93203909  0.74570521  0.2555411  -0.97753012 -0.55068554 -0.49411335]
cos: [ 0.36235775 -0.66627602 -0.96679819 -0.2107958   0.83471278  0.86939749]
tan: [ 2.57215162 -1.11921364 -0.2643169   4.63733205 -0.65973057 -0.56833998]


In [ ]:
#Question: 2

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


matrix = np.array([[4, 5], [7, 4]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(matrix)
round_values = np.round(matrix)


# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)

print("\nround:\n", round_values)

Matrix:
 [[4 5]
 [7 4]]

sin:
 [[-0.7568025  -0.95892427]
 [ 0.6569866  -0.7568025 ]]

cos:
 [[-0.65364362  0.28366219]
 [ 0.75390225 -0.65364362]]

tan:
 [[ 1.15782128 -3.38051501]
 [ 0.87144798  1.15782128]]

asine:
 [[0.60824558 0.79560295]
 [1.57079633 0.60824558]]

acosine:
 [[0.96255075 0.77519337]
 [0.         0.96255075]]

atangent:
 [[1.32581766 1.37340077]
 [1.42889927 1.32581766]]

exp:
 [[  54.59815003  148.4131591 ]
 [1096.63315843   54.59815003]]

log (natural):
 [[1.38629436 1.60943791]
 [1.94591015 1.38629436]]

round:
 [[4 5]
 [7 4]]


In [10]:
# Question: 3

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Creating a 3x2 matrix
matrix = np.array([[-1.2, -2.5], [-3.4, -4.2], [-6.3, -9.1]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(np.abs(matrix))


# Absolute value and square root
abs_values = np.abs(matrix)

sqrt_values = np.sqrt(np.abs(matrix))


# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[-1.2 -2.5]
 [-3.4 -4.2]
 [-6.3 -9.1]]

sin:
 [[-0.93203909 -0.59847214]
 [ 0.2555411   0.87157577]
 [-0.0168139  -0.31909836]]

cos:
 [[ 0.36235775 -0.80114362]
 [-0.96679819 -0.49026082]
 [ 0.99985864 -0.9477216 ]]

tan:
 [[-2.57215162  0.7470223 ]
 [-0.2643169  -1.77777977]
 [-0.01681628  0.33670053]]

asine:
 [[1.57079633 1.57079633]
 [1.57079633 1.57079633]
 [1.57079633 1.57079633]]

acosine:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

atangent:
 [[-0.87605805 -1.19028995]
 [-1.28474489 -1.33705315]
 [-1.41337945 -1.46134538]]

exp:
 [[3.01194212e-01 8.20849986e-02]
 [3.33732700e-02 1.49955768e-02]
 [1.83630478e-03 1.11665808e-04]]

log (natural):
 [[0.18232156 0.91629073]
 [1.22377543 1.43508453]
 [1.84054963 2.20827441]]

abs:
 [[1.2 2.5]
 [3.4 4.2]
 [6.3 9.1]]

sqrt:
 [[1.09544512 1.58113883]
 [1.84390889 2.04939015]
 [2.50998008 3.01662063]]

rem (remainder when divided by 2):
 [[0.8 1.5]
 [0.6 1.8]
 [1.7 0.9]]

round:
 [[-1. -2.]
 [-3. -4.]
 [-6. -9.]]

floor:
 [[ -2.  -3.]
 [ -4

In [ ]:
# Question : 4


import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Sample vector (1D array)
vec = np.array([[1.2,2.2,3.2],[4.2,4.4,5.6]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element
1
# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)



Max value: 5.6 at index 5
Min value: 1.2 at index 0
Length of vector: 2
Sorted vector: [[1.2 2.2 3.2]
 [4.2 4.4 5.6]]
Sum of elements: 20.8
Product of elements: 874.266624
Median value: 3.7
Mean value: 3.466666666666667
Standard deviation: 1.459071241882619
